### ISSUE TITLE
Need to bump required version of impl-service

### ISSUE THREAD

**Issue by Nemo157** [SeunLanLege/arc-reactor#46]
Seems users.rust-lang.org won't let me login using github at the moment, so this is a reply to https://users.rust-lang.org/t/theres-something-weird-going-on-with-cargo-and-proc-macro2/16818

When running `cargo package` Cargo will ignore all path dependencies that have versions specified as well, so it is downloading and using `impl-service` v0.1.0 from crates.io which depends on `proc-macro2` v0.2. You should bump the version of `impl-service` along with the minimum version required by `arc-reactor` then you should get a `` no matching version `^0.1.1` found for package `impl-service` `` error when attempting to package before you publish a new `impl-service` package to crates.io (or 0.2, or whatever you choose the new version to be).

**Comment by SeunLanLege** [comment]
wow thanks a lot :handshake:

**Comment by SeunLanLege** [comment]
done and published :confetti_ball:
